version: '3'

services:
    mariadb:
        image: 'mariadb:10.6.1-focal'
        restart: 'always'

        environment:
            MYSQL_DATABASE: local
            MYSQL_USER: local
            MYSQL_ROOT_PASSWORD: local
            MYSQL_PASSWORD: local
            MYSQL_ROOT_HOST: '%'
        ports:
            - '3306:3306'
