import Head from "next/head";
import { get } from "../src/Api";
import Page from "../src/components/Page";
import { useAppContext } from "../src/context/AppContext";

export default function Home() {
    const demoGet = () => {
        get<{name: string}>("hello", {
            name: "Florin Munteanu"
        }).then((r) => {
            alert(r.name);
        })
    }

    const context = useAppContext();

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page>
                <button onClick={demoGet}> Demo Test</button>
                <p>Current user is {context.user}</p>
            </Page>
        </div>
    );
}
