import Head from "next/head";
import StockCard from "../src/components/StockCard";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <StockCard />
            </main>
        </div>
    );
}
