name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Generate deployment package        
        run: zip -r deploy.zip * .[^.]* -x node_modules/\* -x .git/\*        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: SampleApp
          environment_name: Sampleapp-env
          version_label: ${{env.APP_NAME}}-${{env.PIPELINE_ID}}
          region: us-east-1
          deployment_package: deploy.zip