import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import DynamoDAO from "../services/DynamoDAO"

@table('user')
export class User {
    @autoGeneratedHashKey()
    id!: string;
    
    @attribute({
        type: "Date",
        defaultProvider: () => new Date()
    })
    createdAt!: Date;
}
